### ISSUE TITLE
Unable to build getting error: llvm/IR/Attributes.inc: No such file or directory

### ISSUE THREAD

**Issue by vrnithinkumar** [SVF-tools/SVF#147]
Getting this below error while trying build SVF from source by following the instruction from [Setup-Guide-(CMake)](https://github.com/SVF-tools/SVF/wiki/Setup-Guide-(CMake)).

using gcc 9.1.0
cmake 3.15.2
Also  built LLVM-7.0.0, clang-7.0.0 and added the paths for it.

```
In file included from /llvm-7.0.0.src/include/llvm/IR/Instructions.h:27,
                 from /SVF/include/Util/BasicTypes.h:39,
                 from /SVF/include/Util/SVFModule.h:33,
                 from /SVF/include/Util/SVFUtil.h:33,
                 from /SVF/lib/Util/SVFUtil.cpp:30:
/llvm-7.0.0.src/include/llvm/IR/Attributes.h:74:14: fatal error: llvm/IR/Attributes.inc: No such file or directory
   74 |     #include "llvm/IR/Attributes.inc"
      |              ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by yuleisui** [comment]
The building process works fine at my side, tested on both linux and mac. It seems that the problem is not caused by SVF. But the gcc build for clang.

http://lists.llvm.org/pipermail/llvm-bugs/2015-November/043179.html

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230787

https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg24373.html

Would you be able to build it via clang?

**Comment by vrnithinkumar** [comment]
Yes. I was able to build with clang 7.1.0.
Before that  I was using gcc 9.1.0 to build.
Thanks lot.
