### ISSUE TITLE
compile with gcc 8.2.1 failed, found a bug.

### ISSUE THREAD

**Issue by clarence-glx** [SVF-tools/SVF#651]
/usr/include/c++/8/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [lib/CMakeFiles/Svf.dir/build.make:934: lib/CMakeFiles/Svf.dir/Util/SVFUtil.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:352: lib/CMakeFiles/Svf.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

how to fix it
file: include/Util/SVFUtil.h  line:164 
`typedef OrderedSet<PointsTo, ptsToNodeBS> PointsToList;`
change to
`typedef OrderedSet<PointsTo, equalPointsTo> PointsToList;`

**Comment by yuleisui** [comment]
I didn't find `typedef OrderedSet<PointsTo, ptsToNodeBS> PointsToList;` at SVFUtil.h.

Where is it?

**Comment by yuleisui** [comment]
@mbarbar could you help take a look at this issue?

**Comment by mbarbar** [comment]
Looks like it should be changed to `equalPointsTo`. I'll make a PR.
